# Generated by Django 5.1.5 on 2025-02-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_script_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
